version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_test776060Project
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
